import urllib.parse
from html import escape
from .config import settings

def _e(v):return escape('' if v is None else str(v))
def _site():return {k:settings.get('site.'+k,d) for k,d in [('name','Media Gallery'),('tagline',''),('description',''),('emoji','🖼️'),('theme_color','#7c3aed'),('accent_color','#a78bfa'),('footer_text','')]}
def _layout(title,body,active=''):
 s=_site(); account=''
 if settings.get_bool('accounts.enabled',True):
  if settings.get_bool('accounts.signup_enabled',True):account+='<a href="/signup">Sign up</a>'
  account+='<a href="/user-login">Account</a>'
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="{_e(s['description'])}"><meta name="theme-color" content="{_e(s['theme_color'])}"><title>{_e(title)} · {_e(s['name'])}</title><style>:root{{--theme:{_e(s['theme_color'])};--accent:{_e(s['accent_color'])}}}</style><link rel="stylesheet" href="/static/style.css"><script src="/static/app.js" defer></script>{('<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>' if settings.get_bool('turnstile.enabled',False) else '')}</head><body><header class="topbar"><a class="brand" href="/"><span class="brand-emoji">{_e(s['emoji'])}</span><span><strong>{_e(s['name'])}</strong><small>{_e(s['tagline'])}</small></span></a><nav class="topnav"><a href="/">Gallery</a><a href="/upload">Upload</a>{account}<a href="/admin">Admin</a></nav></header><main>{body}</main><footer class="footer">{_e(s['footer_text'])}</footer></body></html>'''
def _empty_state(title,text,href='',label=''):
 return f'<div class="empty"><h2>{_e(title)}</h2><p>{_e(text)}</p>{f"<a class=\"btn btn-primary\" href=\"{_e(href)}\">{_e(label)}</a>" if href else ""}</div>'
def gallery_page(images,page,pages,reports,sort,q,tag,tags,voting,searching,csrf):
 controls=''
 if searching:
  chips=''.join(f'<a class="tag-chip" href="/?tag={_e(t)}">#{_e(t)}</a>' for t in tags)
  controls=f'''<form class="searchbar" method="get"><input name="q" value="{_e(q)}" maxlength="80" placeholder="Search titles, descriptions and tags"><select name="sort"><option value="new" {"selected" if sort=="new" else ""}>Most recent</option><option value="top" {"selected" if sort=="top" else ""}>Most upvoted</option><option value="hot" {"selected" if sort=="hot" else ""}>Most active</option></select><button class="btn btn-primary" type="submit">Search</button></form><div class="tag-row">{chips}</div>'''
 cards=[]
 for i in images:
  media=f'<img src="/t/{_e(i.uuid)}.webp" alt="{_e(i.title or i.original_filename)}" loading="lazy" decoding="async">' if i.media_type=='image' else (f'<video src="/media/{_e(i.uuid)}" controls preload="metadata"></video>' if i.media_type=='video' else f'<audio src="/media/{_e(i.uuid)}" controls preload="metadata"></audio>')
  tags_html=''.join(f'<a class="tag-chip" href="/?tag={_e(t)}">#{_e(t)}</a>' for t in (i.tags or '').strip(',').split(',') if t)
  tsvote=(f'<div class="cf-turnstile vote-turnstile" data-sitekey="{_e(settings.get('turnstile.site_key',''))}"></div>' if settings.get_bool('turnstile.enabled',False) and settings.get_bool('turnstile.protect_voting',True) else '')
  votes=f'''<form method="post" action="/vote/{_e(i.uuid)}" class="vote-form"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><input type="hidden" name="value" value="1"><input type="text" name="website" tabindex="-1" autocomplete="off" class="honeypot">{tsvote}<button title="Upvote">▲</button></form><strong>{i.upvotes-i.downvotes}</strong><form method="post" action="/vote/{_e(i.uuid)}" class="vote-form"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><input type="hidden" name="value" value="-1"><input type="text" name="website" tabindex="-1" autocomplete="off" class="honeypot">{tsvote}<button title="Downvote">▼</button></form>''' if voting else ''
  cards.append(f'<article class="card"><a class="card-link" href="/media/{_e(i.uuid)}" target="_blank" rel="noopener">{media}</a><div class="card-body"><h2>{_e(i.title or i.original_filename)}</h2><p>{_e(i.description)}</p><div class="tag-row">{tags_html}</div><div class="card-foot"><div class="votes">{votes}</div>{f"<a class=\"report-link\" href=\"/report/{_e(i.uuid)}\">Report</a>" if reports else ''}</div></div></article>')
 grid=''.join(cards) if cards else _empty_state('Nothing here yet','Try another search or be the first to upload something.','/upload','Upload media')
 pager=''
 if pages>1:
  base=f'&q={urllib.parse.quote(q)}&sort={sort}&tag={urllib.parse.quote(tag)}'
  pager=f'<div class="pager">{f"<a class=\"btn\" href=\"/?page={page-1}{base}\">← Newer</a>" if page>1 else ""}<span>Page {page} of {pages}</span>{f"<a class=\"btn\" href=\"/?page={page+1}{base}\">Older →</a>" if page<pages else ""}</div>'
 return _layout('Gallery',f'<section class="hero"><span class="eyebrow">COMMUNITY MEDIA</span><h1>Share. Discover. Vote.</h1><p>Images, audio and video in one lightweight gallery.</p></section>{controls}<div class="masonry">{grid}</div>{pager}')
def upload_page(csrf,error='',turnstile=False):
 ts='<div class="cf-turnstile" data-sitekey="'+_e(settings.get('turnstile.site_key',''))+'"></div><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>' if turnstile and settings.get('turnstile.site_key') else ''
 return _layout('Upload',f'''<h1 class="page-title">Upload media</h1>{f'<div class="notice notice-error">{_e(error)}</div>' if error else ''}<div class="panel"><form action="/upload" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><label class="field"><span>Title</span><input name="title" maxlength="120" placeholder="Give it a title"></label><label class="field"><span>Description</span><textarea name="description" maxlength="1000" rows="4" placeholder="Tell people what this is..."></textarea></label><label class="field"><span>Tags</span><input name="tags" maxlength="300" placeholder="music, meme, sunset"></label><label class="dropzone"><span>Choose image, audio or video</span><input type="file" name="file" accept="image/*,audio/*,video/*" required></label><p class="hint">Files are size-limited and checked before storage. Images are re-encoded to remove metadata.</p>{ts}<button class="btn btn-primary btn-block">Upload</button></form></div>''',active='upload')
def report_page(uid,csrf):return _layout('Report',f'<h1 class="page-title">Report media</h1><div class="panel"><form action="/report/{_e(uid)}" method="post"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><label class="field"><span>Reason</span><select name="reason"><option value="sexual">Sexual content</option><option value="violence">Violence / gore</option><option value="hate">Hate</option><option value="illegal">Illegal content</option><option value="privacy">Privacy violation</option><option value="other">Other</option></select></label><label class="field"><span>Details</span><textarea name="details" maxlength="2000" rows="4"></textarea></label><button class="btn btn-danger">Submit report</button></form></div>')
def login_page(csrf,error=''):return _layout('Admin sign in',f'<h1 class="page-title">Admin sign in</h1>{f"<div class=\"notice notice-error\">{_e(error)}</div>" if error else ""}<div class="panel panel-narrow"><form action="/login" method="post"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><label class="field"><span>Password</span><input type="password" name="password" autocomplete="current-password" required autofocus></label><button class="btn btn-primary btn-block">Sign in</button></form></div>')
def signup_page(csrf,error='',turnstile=False):
 ts='<div class="cf-turnstile" data-sitekey="'+_e(settings.get('turnstile.site_key',''))+'"></div><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>' if turnstile and settings.get('turnstile.site_key') else ''
 return _layout('Create account',f'<h1 class="page-title">Create your account</h1>{f"<div class=\"notice notice-error\">{_e(error)}</div>" if error else ""}<div class="panel panel-narrow"><form action="/signup" method="post"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><label class="field"><span>Username</span><input name="username" pattern="[A-Za-z0-9_]+" minlength="3" maxlength="24" required autocomplete="username"></label><label class="field"><span>Password</span><input type="password" name="password" minlength="10" maxlength="128" required autocomplete="new-password"></label><label class="field"><span>Confirm password</span><input type="password" name="confirm_password" minlength="10" maxlength="128" required autocomplete="new-password"></label>{ts}<button class="btn btn-primary btn-block">Create account</button></form></div>')
def user_login_page(csrf,error=''):return _layout('Sign in',f'<h1 class="page-title">Sign in</h1>{f"<div class=\"notice notice-error\">{_e(error)}</div>" if error else ""}<div class="panel panel-narrow"><form action="/user-login" method="post"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><label class="field"><span>Username</span><input name="username" required></label><label class="field"><span>Password</span><input type="password" name="password" required></label><button class="btn btn-primary btn-block">Sign in</button></form></div>')
def user_account_page(username,csrf):return _layout('Account',f'<section class="hero"><span class="eyebrow">ACCOUNT</span><h1>Welcome, {_e(username)}</h1><p>Your account can be attached to posts and votes.</p><form method="post" action="/account/logout"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><button class="btn btn-ghost">Sign out</button></form></section>')
def admin_page(q,r,csrf,stop,blur=True):
 def block(i):return f'<div class="admin-card"><img class="thumb{" thumb-blur" if blur else ""}" src="/admin/thumb/{_e(i.uuid)}"><div class="admin-card-meta"><strong>{_e(i.title or i.original_filename)}</strong><span>Score: {_e(i.moderation_score)}</span><span>Reports: {i.reports_count}</span><div class="admin-actions"><form method="post" action="/admin/approve/{_e(i.uuid)}"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><button class="btn btn-approve btn-sm">Approve</button></form><form method="post" action="/admin/reject/{_e(i.uuid)}"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><button class="btn btn-danger btn-sm">Reject</button></form></div></div></div>'
 return _layout('Admin',f'<div class="admin-head"><h1 class="page-title">Admin dashboard</h1><form method="post" action="/admin/emergency_toggle"><input type="hidden" name="csrf_token" value="{_e(csrf)}"><button class="btn">{"Disable uploads" if not stop else "Enable uploads"}</button></form></div><h2 class="section-title">Quarantine ({len(q)})</h2><div class="admin-grid">{"".join(block(i) for i in q) or _empty_state("Queue clear","Nothing needs review.")}</div><h2 class="section-title">Reported ({len(r)})</h2><div class="admin-grid">{"".join(block(i) for i in r) or _empty_state("No reports","Nothing reported.")}</div>')
def message_page(title,text):return _layout(title,_empty_state(title,text))
